### ISSUE TITLE
Prompt for confirmation before proceeding with a "dangerous" action

### ISSUE THREAD

**Issue by mjtko** [openflighthpc/flight-action#4]
Would be useful to prompt the user before proceeding with something that might be destructive.

e.g. power cycling or powering off a node spring to mind

Something like:

```
$ flight power off cnode01
Power off cnode01, confirm to proceed (Y/N) [N]?
Cancelled power off request.
```

```
$ flight power off cnode01
Power off cnode01, confirm to proceed (Y/N) [N]? y
Proceeding with request.
OK
```

Those words aren't great, better ones would be good!

Related: able to override at command line `flight power off cnode01 --confirm`

**Comment by WilliamMcCumstie** [comment]
This has been implemented circa: https://github.com/openflighthpc/flight-action/releases/tag/1.1.0
