### ISSUE TITLE
Improve option help text

### ISSUE THREAD

**Issue by mjtko** [openflighthpc/flight-action#5]
At the moment it says things like:

```
   -g, --group
        Run over the group of nodes given by NAME

    -o, --output DIRECTORY
        Save the results within the given directory

    --[no-]prefix
        Disable hostname: prefix on lines of output.

    -S
        Return the largest of the command return values.

    --[no-]stdout
        Display stdout

    --[no-]stderr
        Display stderr
```

I think some of these could be better described to indicate intended use and results.

**Comment by benarmston** [comment]
The options `--output`, `--prefix`, `-S`, `--stdout` and `--stderr` were all dropped with the introduction of streaming support.  I think the help text for the remaining `--group` option is good.
